add Licenses View Controller
cforlando/PetAdoption-iOS pull request #94
Opened 2018-07-04 00:48 UTC by amirfl

![screen shot 2018-07-03 at 8 48 06 pm](https://user-images.githubusercontent.com/364326/42250925-6ab23f9c-7f02-11e8-8115-b4dfeccb147a.png)

![screen shot 2018-07-03 at 8 46 28 pm](https://user-images.githubusercontent.com/364326/42250911-531f6062-7f02-11e8-85f8-cc7a8034aa47.png)

2018-07-04 14:15 UTC, WERUreo requested changes

2018-07-04 14:15 UTC, WERUreo commented on PetAdoption-iOS/PetAdoption-iOS/LicensesViewController.swift
> +struct item {
The only criticism I would have is that the convention is to capitalize classes and structs
> Whenever you define a new structure or class, you define a new Swift type. Give types UpperCamelCase names (such as SomeStructure and SomeClass here) to match the capitalization of standard Swift types (such as String, Int, and Bool). Give properties and methods lowerCamelCase names (such as frameRate and incrementCount) to differentiate them from type names.

> https://docs.swift.org/swift-book/LanguageGuide/ClassesAndStructures.html

Other than that, looks good!

2018-07-05 22:04 UTC, amirfl commented
Thanks for the review.

Changed "item" to "Item". Also added a few more licenses, not sure if I got all of the 3rd licenses we are using.
Also refactored so that the detail text of each license fits in the table view cell.

![simulator screen shot - iphone 8 plus - 2018-07-05 at 18 02 47](https://user-images.githubusercontent.com/364326/42350259-abb7b7de-807d-11e8-9f3f-a219a9bc3139.png)

2018-07-12 01:15 UTC, WERUreo approved these changes

2018-07-12 01:16 UTC, WERUreo commented
Looks good.  Thanks!

2018-07-12 01:16 UTC, merged